# fly.toml

app = "carim-y-nntg"          # ← zmień jeśli nazwa inna
primary_region = "ams"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  app = "python main.py"

# Bot ma działać 24/7
auto_stop_machines  = false
auto_start_machines = true
min_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus     = 1
  memory   = "256mb"
